### PR TITLE
Fugbix typo.

### PR DESCRIPTION
**Pull request by whatthejeff**
anigif_enhanced-buzz-654-1334931902-8

### CODE REVIEW

**Comment by igorw** [comment]
serious business, wanna update composer.json too?

**Comment by whatthejeff** [comment]
Sure, but it will cost you a gif of equivalent awesomeness.

**Comment by igorw** [comment]
I'll see what I can do

**Comment by JesseObrien** [comment]
cat-powers

**Comment by whatthejeff** [comment]
Nicely done, gents.

**Comment by igorw** [comment]
damnit broke my streak of not committing on github

**Comment by whatthejeff** [comment]
October on my contributions calendar should be a good source of inspiration :)

**Pull request merged**
